### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by btd1337** [artemanufrij/imageburner#45]
Which is this package?

```
CMake Error at CMakeLists.txt:32 (include):
  include could not find load file:

    ValaPrecompile


CMake Error at CMakeLists.txt:33 (find_package):
  By not providing "FindVala.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Vala", but
  CMake did not find one.

  Could not find a package configuration file provided by "Vala" with any of
  the following names:

    ValaConfig.cmake
    vala-config.cmake

  Add the installation prefix of "Vala" to CMAKE_PREFIX_PATH or set
  "Vala_DIR" to a directory containing one of the above files.  If "Vala"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
```

**Comment by TeddyDD** [comment]
I'v got the same problem. It seems we need [elementary Cmake modules](https://github.com/elementary/junk/tree/cmake-modules) but they are deprecated (also not packaged for many distros)

Since elementary is moving to meson, I wonder if it wound't be good direction for Imageburner as well. It would simplify building this project on other distros.

I did quick conversion from CMake to meson, and Imageburner builds fine, but someone more familiar with meson and this project should take a look. I can submit PR if @artemanufrij is willing to switch build system. WDYT?

**Comment by artemanufrij** [comment]
@TeddyDD It would be very helpful !
